Copyright (C) 2020 Edouard Fouch√©

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

In [1]:
import math

import matplotlib as mpl
from matplotlib import cm
mpl.rcParams['text.usetex'] = True 
mpl.rcParams['text.latex.preamble'] = r'\usepackage{libertine}' 
mpl.rc('font', family='serif')

import numpy as np
import pandas as pd
import seaborn as sns
import copy

import matplotlib.pyplot as plt
from matplotlib import rc

from cycler import cycler

mpl.rcParams['ps.usedistiller'] = 'xpdf' 
plt.style.use('seaborn-notebook')

plt.rcParams['axes.titlesize'] = '25'
plt.rcParams['axes.labelsize'] = '25'
plt.rcParams['legend.fontsize'] = '15'
plt.rcParams['xtick.labelsize'] = '15'
plt.rcParams['ytick.labelsize'] = '15'

monochrome=(cycler('color', sns.color_palette("husl", 8))*2+(cycler('marker', ['v', 's', "o"])*7)[0:16])
plt.rc('axes', prop_cycle=monochrome)

pd.options.display.max_rows = 999
pd.options.display.max_columns = None
cmap = cm.get_cmap('RdBu')

In [2]:
folder = "2020-02-10-17-37_Ablation_" # Replace

In [3]:
masterdata = pd.read_csv("../experiments/" + folder + "/Ablation.csv")

In [4]:
masterdata.columns

Index(['scoreId', 'dataset', 'bmId', 'k', 'j', 'nwords', 'ndocs', 'emb', 'cpu',
       'wall', 'cpurep', 'cpuindex', 'cpucache', 'c', 'p', 'entropythreshold',
       'miss', 'typeBrecall', 'typeBprecision', 'typeArecall',
       'typeAprecision', 'typeAauc', 'typeAap', 'typeBr1', 'typeBr2',
       'typeBr5', 'typeBr10', 'typeBr20', 'typeBr30', 'typeBp1', 'typeBp2',
       'typeBp5', 'typeBp10', 'typeBp20', 'typeBp30', 'typeBr1N', 'typeBr2N',
       'typeBr5N', 'typeBr10N', 'typeBr20N', 'typeBr30N', 'typeBp1N',
       'typeBp2N', 'typeBp5N', 'typeBp10N', 'typeBp20N', 'typeBp30N',
       'typeAr1', 'typeAr2', 'typeAr5', 'typeAr10', 'typeAr20', 'typeAr30',
       'typeAp1', 'typeAp2', 'typeAp5', 'typeAp10', 'typeAp20', 'typeAp30',
       'avgmiss', 'stdmiss', 'avgmatch', 'stdmatch', 'rep'],
      dtype='object')

In [5]:
masterdata["p"].unique()

array([ 0.  ,  0.01,  0.02,  0.05,  0.1 ,  0.2 ,  0.3 ,  0.4 ,  0.5 ,
        0.6 ,  0.7 ,  0.8 ,  0.9 ,  0.95,  0.98,  1.  ])

In [6]:
masterdata["c"].unique()

array([ 0.1 ,  0.2 ,  0.  ,  0.05,  0.3 ])

In [7]:
masterdata["rep"].unique()

array([1, 2, 4, 3, 5])

In [8]:
masterdata["dataset"].unique()

array(['arxiv_15', 'arxiv_25', 'arxiv_35', 'nyt_10', 'arxiv_45',
       'arxiv_54', 'arxiv_52', 'arxiv_53', 'arxiv_55', 'arxiv_51',
       'nyt_20', 'nyt_50', 'nyt_2', 'nyt_1', 'nyt_5'], dtype=object)

In [9]:
masterdata["k"].unique()

array([ 0, 30])

In [10]:
masterdata["j"].unique()

array([ 0, 30])

In [11]:
masterdata["scoreId"].unique()

array(['KJNN', 'WKJNN'], dtype=object)

In [12]:
subdata = masterdata[(masterdata["c"] == 0.2)& ([x in [0.9, 1.0] for x in masterdata["p"]])]

In [13]:
subdata["A-F1"] = 2* (subdata["typeArecall"]*subdata["typeAprecision"]) / (subdata["typeArecall"]+subdata["typeAprecision"])
subdata["B-F1"] = 2* (subdata["typeBrecall"]*subdata["typeBprecision"]) / (subdata["typeBrecall"]+subdata["typeBprecision"])

/home/fouchee/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/home/fouchee/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [14]:
subdata["A"] = ["0" for x in subdata.index]

/home/fouchee/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [15]:
A4index = (subdata["scoreId"] == "KJNN") & (subdata["k"] == 30) & (subdata["j"] == 30) & (subdata["c"] == 0.2) & (subdata["p"] == 0.9)
A3index = (subdata["scoreId"] == "WKJNN") & (subdata["k"] == 0) & (subdata["j"] == 30) & (subdata["c"] == 0.2) & (subdata["p"] == 0.9)
A2index = (subdata["scoreId"] == "WKJNN") & (subdata["k"] == 30) & (subdata["j"] == 30) & (subdata["c"] == 0.2) & (subdata["p"] == 1.0)
A1index = (subdata["scoreId"] == "WKJNN") & (subdata["k"] == 30) & (subdata["j"] == 0) & (subdata["c"] == 0.2) & (subdata["p"] == 0.9)
kjNNind = (subdata["scoreId"] == "WKJNN") & (subdata["k"] == 30) & (subdata["j"] == 30) & (subdata["c"] == 0.2) & (subdata["p"] == 0.9)

subdata["A"][A4index] = "A4"
subdata["A"][A3index] = "A3"
subdata["A"][A2index] = "A2"
subdata["A"][A1index] = "A1"
subdata["A"][kjNNind] = "kj-NN"

/home/fouchee/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/home/fouchee/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:9114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)
/home/fouchee/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2961: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
/home/fouchee/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/fouchee/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/home/fouchee/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/home/fouchee/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

In [16]:
subdata = subdata[subdata["A"] != "0"]

In [17]:
attsmall = ['typeAprecision', 'typeArecall', "A-F1", 
       'typeBprecision', 'typeBrecall', "B-F1", "typeBr10", "typeBr20"]
att = ['typeAprecision', 'typeArecall', "A-F1", 
       'typeBprecision', 'typeBrecall', "B-F1", 
       "typeAauc", "typeAap", "typeAr1", "typeAr2", "typeAr5",
      "typeBr10", "typeBr20"]
times = ['cpu', 'wall', 'cpurep', 'cpuindex', 'cpucache']

output = subdata.groupby(["dataset", "A", "scoreId", "p", "c", "j", "k"])[att + times].mean()


output[att] = round(output[att]*100,2)


output[times] = round(output[times] / 1000,2)

output[attsmall]

                                      typeAprecision  typeArecall   A-F1  \
dataset  A     scoreId p   c   j  k
arxiv_15 A1    WKJNN   0.9 0.2 0  30            0.00         0.00    NaN
         A2    WKJNN   1.0 0.2 30 30            0.00         0.00    NaN
         A3    WKJNN   0.9 0.2 30 0             0.00         0.00    NaN
         A4    KJNN    0.9 0.2 30 30            0.00         0.00    NaN
         kj-NN WKJNN   0.9 0.2 30 30            0.00         0.00    NaN
arxiv_25 A1    WKJNN   0.9 0.2 0  30            3.22        32.17   5.86
         A2    WKJNN   1.0 0.2 30 30            0.00         0.00    NaN
         A3    WKJNN   0.9 0.2 30 0             5.01        50.00   9.11
         A4    KJNN    0.9 0.2 30 30            3.88        38.70   7.05
         kj-NN WKJNN   0.9 0.2 30 30            3.88        38.70   7.05
arxiv_35 A1    WKJNN   0.9 0.2 0  30            2.86        28.71   5.20
         A2    WKJNN   1.0 0.2 30 30            0.00         0.00    NaN
         A3    WKJNN   0.9 0.2 30 0             3.05        30.65   5.55
         A4    KJNN    0.9 0.2 30 30            2.99        30.00   5.43
         kj-NN WKJNN   0.9 0.2 30 30            3.05        30.65   5.55
arxiv_45 A1    WKJNN   0.9 0.2 0  30            3.16        31.92   5.75
         A2    WKJNN   1.0 0.2 30 30            0.00         0.00    NaN
         A3    WKJNN   0.9 0.2 30 0             3.18        32.12   5.79
         A4    KJNN    0.9 0.2 30 30            3.14        31.71   5.71
         kj-NN WKJNN   0.9 0.2 30 30            3.12        31.51   5.68
arxiv_51 A1    WKJNN   0.9 0.2 0  30            3.03        30.65   5.51
         A2    WKJNN   1.0 0.2 30 30            0.00         0.00    NaN
         A3    WKJNN   0.9 0.2 30 0             0.72         7.26   1.31
         A4    KJNN    0.9 0.2 30 30            2.45        24.84   4.47
         kj-NN WKJNN   0.9 0.2 30 30            2.52        25.48   4.58
arxiv_52 A1    WKJNN   0.9 0.2 0  30            3.42        34.68   6.23
         A2    WKJNN   1.0 0.2 30 30            0.00         0.00    NaN
         A3    WKJNN   0.9 0.2 30 0             1.15        11.61   2.09
         A4    KJNN    0.9 0.2 30 30            3.45        35.00   6.29
         kj-NN WKJNN   0.9 0.2 30 30            3.49        35.32   6.35
arxiv_53 A1    WKJNN   0.9 0.2 0  30            4.73        47.90   8.61
         A2    WKJNN   1.0 0.2 30 30            0.00         0.00    NaN
         A3    WKJNN   0.9 0.2 30 0             3.52        35.64   6.40
         A4    KJNN    0.9 0.2 30 30            4.99        50.48   9.08
         kj-NN WKJNN   0.9 0.2 30 30            4.92        49.84   8.96
arxiv_54 A1    WKJNN   0.9 0.2 0  30            3.48        35.32   6.34
         A2    WKJNN   1.0 0.2 30 30            0.00         0.00    NaN
         A3    WKJNN   0.9 0.2 30 0             3.29        33.38   5.99
         A4    KJNN    0.9 0.2 30 30            3.66        37.10   6.66
         kj-NN WKJNN   0.9 0.2 30 30            3.68        37.26   6.69
arxiv_55 A1    WKJNN   0.9 0.2 0  30            3.33        33.71   6.06
         A2    WKJNN   1.0 0.2 30 30            0.00         0.00    NaN
         A3    WKJNN   0.9 0.2 30 0             2.84        28.71   5.17
         A4    KJNN    0.9 0.2 30 30            3.49        35.32   6.35
         kj-NN WKJNN   0.9 0.2 30 30            3.50        35.48   6.37
nyt_1    A1    WKJNN   0.9 0.2 0  30            7.17        72.40  13.05
         A2    WKJNN   1.0 0.2 30 30            0.00         0.00    NaN
         A3    WKJNN   0.9 0.2 30 0             6.63        67.00  12.07
         A4    KJNN    0.9 0.2 30 30            7.66        77.40  13.94
         kj-NN WKJNN   0.9 0.2 30 30            7.70        77.80  14.01
nyt_10   A1    WKJNN   0.9 0.2 0  30            6.14        62.00  11.17
         A2    WKJNN   1.0 0.2 30 30            0.00         0.00    NaN
         A3    WKJNN   0.9 0.2 30 0             5.15        52.00   9.37
         A4    KJNN    0.9 0.2 30 30            5.94        60.00  10.81
         kj-NN WKJNN   0.9 0.2 30 30            6.14        62.00  11.17
nyt_2    A1    WKJNN   0.9 0.2 0  30           15.63        79.70  26.13
         A2    WKJNN   1.0 0.2 30 30            0.00         0.00    NaN
         A3    WKJNN   0.9 0.2 30 0            13.65        69.60  22.82
         A4    KJNN    0.9 0.2 30 30           15.71        80.10  26.27
         kj-NN WKJNN   0.9 0.2 30 30           15.67        79.90  26.20
nyt_20   A1    WKJNN   0.9 0.2 0  30            6.34        64.00  11.53
         A2    WKJNN   1.0 0.2 30 30            0.00         0.00    NaN
         A3    WKJNN   0.9 0.2 30 0             5.75        58.00  10.46
         A4    KJNN    0.9 0.2 30 30            6.44        65.00  11.72
         kj-NN WKJNN   0.9 0.2 30 30            6.44        65.00  11.72
nyt_5    A1    WKJNN   0.9 0.2 0  30           41.20        86.52  55.82
         A2    WKJNN   1.0 0.2 30 30            0.00         0.00    NaN
         A3    WKJNN   0.9 0.2 30 0            31.85        66.88  43.15
         A4    KJNN    0.9 0.2 30 30           40.86        85.80  55.36
         kj-NN WKJNN   0.9 0.2 30 30           40.93        85.96  55.46
nyt_50   A1    WKJNN   0.9 0.2 0  30            7.76        78.40  14.12
         A2    WKJNN   1.0 0.2 30 30            0.00         0.00    NaN
         A3    WKJNN   0.9 0.2 30 0             7.33        74.00  13.33
         A4    KJNN    0.9 0.2 30 30            7.96        80.40  14.49
         kj-NN WKJNN   0.9 0.2 30 30            7.92        80.00  14.41

                                      typeBprecision  typeBrecall   B-F1  \
dataset  A     scoreId p   c   j  k
arxiv_15 A1    WKJNN   0.9 0.2 0  30            0.00         0.00    NaN
         A2    WKJNN   1.0 0.2 30 30            0.00         0.00    NaN
         A3    WKJNN   0.9 0.2 30 0             0.00         0.00    NaN
         A4    KJNN    0.9 0.2 30 30            0.00         0.00    NaN
         kj-NN WKJNN   0.9 0.2 30 30            0.00         0.00    NaN
arxiv_25 A1    WKJNN   0.9 0.2 0  30           95.01        88.93  91.87
         A2    WKJNN   1.0 0.2 30 30           91.22        98.17  94.56
         A3    WKJNN   0.9 0.2 30 0            97.30        88.16  92.50
         A4    KJNN    0.9 0.2 30 30           96.10        88.98  92.40
         kj-NN WKJNN   0.9 0.2 30 30           96.09        88.85  92.33
arxiv_35 A1    WKJNN   0.9 0.2 0  30           80.03        87.14  83.43
         A2    WKJNN   1.0 0.2 30 30           72.75        95.60  82.62
         A3    WKJNN   0.9 0.2 30 0            71.60        84.32  77.44
         A4    KJNN    0.9 0.2 30 30           79.92        86.99  83.30
         kj-NN WKJNN   0.9 0.2 30 30           80.04        86.98  83.36
arxiv_45 A1    WKJNN   0.9 0.2 0  30           70.02        86.64  77.45
         A2    WKJNN   1.0 0.2 30 30           63.93        95.41  76.56
         A3    WKJNN   0.9 0.2 30 0            65.43        84.83  73.87
         A4    KJNN    0.9 0.2 30 30           70.09        86.88  77.59
         kj-NN WKJNN   0.9 0.2 30 30           70.29        86.87  77.70
arxiv_51 A1    WKJNN   0.9 0.2 0  30           70.76        88.33  78.58
         A2    WKJNN   1.0 0.2 30 30           63.81        96.89  76.94
         A3    WKJNN   0.9 0.2 30 0            65.83        86.86  74.90
         A4    KJNN    0.9 0.2 30 30           70.80        88.68  78.74
         kj-NN WKJNN   0.9 0.2 30 30           70.91        88.63  78.79
arxiv_52 A1    WKJNN   0.9 0.2 0  30           70.86        88.53  78.71
         A2    WKJNN   1.0 0.2 30 30           63.76        96.73  76.85
         A3    WKJNN   0.9 0.2 30 0            65.85        86.51  74.78
         A4    KJNN    0.9 0.2 30 30           70.90        88.45  78.71
         kj-NN WKJNN   0.9 0.2 30 30           71.08        88.43  78.81
arxiv_53 A1    WKJNN   0.9 0.2 0  30           70.58        88.35  78.47
         A2    WKJNN   1.0 0.2 30 30           63.54        96.75  76.71
         A3    WKJNN   0.9 0.2 30 0            65.89        86.98  74.98
         A4    KJNN    0.9 0.2 30 30           70.65        88.51  78.58
         kj-NN WKJNN   0.9 0.2 30 30           70.77        88.46  78.63
arxiv_54 A1    WKJNN   0.9 0.2 0  30           70.19        87.95  78.07
         A2    WKJNN   1.0 0.2 30 30           63.38        96.94  76.65
         A3    WKJNN   0.9 0.2 30 0            66.09        86.68  75.00
         A4    KJNN    0.9 0.2 30 30           70.19        88.01  78.10
         kj-NN WKJNN   0.9 0.2 30 30           70.38        88.05  78.23
arxiv_55 A1    WKJNN   0.9 0.2 0  30           70.33        88.24  78.27
         A2    WKJNN   1.0 0.2 30 30           63.78        96.82  76.90
         A3    WKJNN   0.9 0.2 30 0            66.06        87.02  75.10
         A4    KJNN    0.9 0.2 30 30           70.49        88.19  78.35
         kj-NN WKJNN   0.9 0.2 30 30           70.70        88.23  78.50
nyt_1    A1    WKJNN   0.9 0.2 0  30           94.56        90.04  92.25
         A2    WKJNN   1.0 0.2 30 30           86.43        99.07  92.32
         A3    WKJNN   0.9 0.2 30 0            91.85        89.28  90.54
         A4    KJNN    0.9 0.2 30 30           95.88        90.00  92.85
         kj-NN WKJNN   0.9 0.2 30 30           95.93        90.02  92.88
nyt_10   A1    WKJNN   0.9 0.2 0  30           88.18        90.47  89.31
         A2    WKJNN   1.0 0.2 30 30           80.98        98.50  88.88
         A3    WKJNN   0.9 0.2 30 0            87.30        85.17  86.20
         A4    KJNN    0.9 0.2 30 30           88.19        90.57  89.36
         kj-NN WKJNN   0.9 0.2 30 30           88.57        90.77  89.65
nyt_2    A1    WKJNN   0.9 0.2 0  30           93.61        91.23  92.40
         A2    WKJNN   1.0 0.2 30 30           83.15        99.32  90.52
         A3    WKJNN   0.9 0.2 30 0            90.22        89.89  90.05
         A4    KJNN    0.9 0.2 30 30           94.55        91.07  92.78
         kj-NN WKJNN   0.9 0.2 30 30           94.63        91.15  92.86
nyt_20   A1    WKJNN   0.9 0.2 0  30           93.10        90.29  91.67
         A2    WKJNN   1.0 0.2 30 30           83.56        98.90  90.58
         A3    WKJNN   0.9 0.2 30 0            91.19        87.44  89.27
         A4    KJNN    0.9 0.2 30 30           93.60        90.49  92.02
         kj-NN WKJNN   0.9 0.2 30 30           93.80        90.64  92.19
nyt_5    A1    WKJNN   0.9 0.2 0  30           92.12        93.55  92.83
         A2    WKJNN   1.0 0.2 30 30           75.92        99.18  86.01
         A3    WKJNN   0.9 0.2 30 0            86.12        91.97  88.95
         A4    KJNN    0.9 0.2 30 30           92.23        93.45  92.84
         kj-NN WKJNN   0.9 0.2 30 30           92.43        93.44  92.93
nyt_50   A1    WKJNN   0.9 0.2 0  30           94.20        90.36  92.24
         A2    WKJNN   1.0 0.2 30 30           85.40        99.34  91.84
         A3    WKJNN   0.9 0.2 30 0            92.68        89.11  90.86
         A4    KJNN    0.9 0.2 30 30           95.64        90.34  92.91
         kj-NN WKJNN   0.9 0.2 30 30           95.78        90.36  92.99

                                      typeBr10  typeBr20
dataset  A     scoreId p   c   j  k
arxiv_15 A1    WKJNN   0.9 0.2 0  30      0.00      0.00
         A2    WKJNN   1.0 0.2 30 30      0.00      0.00
         A3    WKJNN   0.9 0.2 30 0       0.00      0.00
         A4    KJNN    0.9 0.2 30 30      0.00      0.00
         kj-NN WKJNN   0.9 0.2 30 30      0.00      0.00
arxiv_25 A1    WKJNN   0.9 0.2 0  30     49.02     88.93
         A2    WKJNN   1.0 0.2 30 30     49.22     95.48
         A3    WKJNN   0.9 0.2 30 0      49.90     88.16
         A4    KJNN    0.9 0.2 30 30     49.22     88.98
         kj-NN WKJNN   0.9 0.2 30 30     49.22     88.85
arxiv_35 A1    WKJNN   0.9 0.2 0  30     47.20     83.05
         A2    WKJNN   1.0 0.2 30 30     48.25     83.40
         A3    WKJNN   0.9 0.2 30 0      45.40     76.64
         A4    KJNN    0.9 0.2 30 30     48.24     83.32
         kj-NN WKJNN   0.9 0.2 30 30     48.25     83.40
arxiv_45 A1    WKJNN   0.9 0.2 0  30     44.52     76.30
         A2    WKJNN   1.0 0.2 30 30     45.78     76.89
         A3    WKJNN   0.9 0.2 30 0      42.60     72.36
         A4    KJNN    0.9 0.2 30 30     45.72     76.70
         kj-NN WKJNN   0.9 0.2 30 30     45.78     76.89
arxiv_51 A1    WKJNN   0.9 0.2 0  30     45.16     77.85
         A2    WKJNN   1.0 0.2 30 30     46.25     78.18
         A3    WKJNN   0.9 0.2 30 0      43.46     74.00
         A4    KJNN    0.9 0.2 30 30     46.19     78.09
         kj-NN WKJNN   0.9 0.2 30 30     46.25     78.18
arxiv_52 A1    WKJNN   0.9 0.2 0  30     46.19     78.12
         A2    WKJNN   1.0 0.2 30 30     47.28     78.79
         A3    WKJNN   0.9 0.2 30 0      44.23     73.92
         A4    KJNN    0.9 0.2 30 30     47.22     78.57
         kj-NN WKJNN   0.9 0.2 30 30     47.28     78.79
arxiv_53 A1    WKJNN   0.9 0.2 0  30     45.62     77.66
         A2    WKJNN   1.0 0.2 30 30     46.69     78.24
         A3    WKJNN   0.9 0.2 30 0      44.01     74.33
         A4    KJNN    0.9 0.2 30 30     46.66     78.19
         kj-NN WKJNN   0.9 0.2 30 30     46.69     78.24
arxiv_54 A1    WKJNN   0.9 0.2 0  30     45.60     77.48
         A2    WKJNN   1.0 0.2 30 30     46.83     77.78
         A3    WKJNN   0.9 0.2 30 0      43.93     73.63
         A4    KJNN    0.9 0.2 30 30     46.80     77.65
         kj-NN WKJNN   0.9 0.2 30 30     46.83     77.78
arxiv_55 A1    WKJNN   0.9 0.2 0  30     45.80     78.04
         A2    WKJNN   1.0 0.2 30 30     46.77     78.67
         A3    WKJNN   0.9 0.2 30 0      43.88     73.70
         A4    KJNN    0.9 0.2 30 30     46.70     78.49
         kj-NN WKJNN   0.9 0.2 30 30     46.77     78.67
nyt_1    A1    WKJNN   0.9 0.2 0  30     49.76     90.04
         A2    WKJNN   1.0 0.2 30 30     50.19     94.04
         A3    WKJNN   0.9 0.2 30 0      49.95     89.28
         A4    KJNN    0.9 0.2 30 30     50.18     90.00
         kj-NN WKJNN   0.9 0.2 30 30     50.19     90.02
nyt_10   A1    WKJNN   0.9 0.2 0  30     49.50     89.77
         A2    WKJNN   1.0 0.2 30 30     50.50     90.07
         A3    WKJNN   0.9 0.2 30 0      49.30     85.17
         A4    KJNN    0.9 0.2 30 30     50.50     89.77
         kj-NN WKJNN   0.9 0.2 30 30     50.50     89.97
nyt_2    A1    WKJNN   0.9 0.2 0  30     50.37     91.23
         A2    WKJNN   1.0 0.2 30 30     50.74     94.07
         A3    WKJNN   0.9 0.2 30 0      50.64     89.89
         A4    KJNN    0.9 0.2 30 30     50.76     91.07
         kj-NN WKJNN   0.9 0.2 30 30     50.74     91.15
nyt_20   A1    WKJNN   0.9 0.2 0  30     50.27     90.29
         A2    WKJNN   1.0 0.2 30 30     50.52     92.60
         A3    WKJNN   0.9 0.2 30 0      50.08     87.44
         A4    KJNN    0.9 0.2 30 30     50.52     90.49
         kj-NN WKJNN   0.9 0.2 30 30     50.52     90.64
nyt_5    A1    WKJNN   0.9 0.2 0  30     51.86     93.55
         A2    WKJNN   1.0 0.2 30 30     52.27     95.14
         A3    WKJNN   0.9 0.2 30 0      52.20     91.16
         A4    KJNN    0.9 0.2 30 30     52.26     93.45
         kj-NN WKJNN   0.9 0.2 30 30     52.27     93.44
nyt_50   A1    WKJNN   0.9 0.2 0  30     49.96     90.36
         A2    WKJNN   1.0 0.2 30 30     50.22     93.76
         A3    WKJNN   0.9 0.2 30 0      50.26     89.11
         A4    KJNN    0.9 0.2 30 30     50.20     90.34
         kj-NN WKJNN   0.9 0.2 30 30     50.22     90.36

In [18]:
output = subdata.groupby(["dataset", "A", "scoreId", "p", "c", "j", "k"])[att + times].mean()

attsmall = ['typeAprecision', 'typeArecall', "A-F1", 
       'typeBprecision', 'typeBrecall', "B-F1"]
att = ['typeAprecision', 'typeArecall', "A-F1", 
       'typeBprecision', 'typeBrecall', "B-F1", 
       "typeAauc", "typeAap", "typeAr1", "typeAr2", "typeAr5",
      "typeBr10", "typeBr20"]
output[att] = round(output[att]*100,2)

times = ['cpu', 'wall', 'cpurep', 'cpuindex', 'cpucache']
output[times] = round(output[times] / 1000,2)

output[["typeAauc", "typeAap"]]

                                      typeAauc  typeAap
dataset  A     scoreId p   c   j  k
arxiv_15 A1    WKJNN   0.9 0.2 0  30     54.21     1.17
         A2    WKJNN   1.0 0.2 30 30     54.21     1.17
         A3    WKJNN   0.9 0.2 30 0      54.21     1.17
         A4    KJNN    0.9 0.2 30 30     54.21     1.17
         kj-NN WKJNN   0.9 0.2 30 30     54.21     1.17
arxiv_25 A1    WKJNN   0.9 0.2 0  30     67.75     3.70
         A2    WKJNN   1.0 0.2 30 30     70.64     5.10
         A3    WKJNN   0.9 0.2 30 0      81.23     5.93
         A4    KJNN    0.9 0.2 30 30     70.48     5.09
         kj-NN WKJNN   0.9 0.2 30 30     70.64     5.10
arxiv_35 A1    WKJNN   0.9 0.2 0  30     71.98     3.02
         A2    WKJNN   1.0 0.2 30 30     73.58     3.27
         A3    WKJNN   0.9 0.2 30 0      74.14     2.72
         A4    KJNN    0.9 0.2 30 30     73.54     3.27
         kj-NN WKJNN   0.9 0.2 30 30     73.58     3.27
arxiv_45 A1    WKJNN   0.9 0.2 0  30     69.42     2.96
         A2    WKJNN   1.0 0.2 30 30     69.94     3.28
         A3    WKJNN   0.9 0.2 30 0      71.56     3.17
         A4    KJNN    0.9 0.2 30 30     69.88     3.27
         kj-NN WKJNN   0.9 0.2 30 30     69.94     3.28
arxiv_51 A1    WKJNN   0.9 0.2 0  30     68.41     3.03
         A2    WKJNN   1.0 0.2 30 30     65.24     2.19
         A3    WKJNN   0.9 0.2 30 0      57.35     1.12
         A4    KJNN    0.9 0.2 30 30     64.76     2.11
         kj-NN WKJNN   0.9 0.2 30 30     65.24     2.19
arxiv_52 A1    WKJNN   0.9 0.2 0  30     77.44     3.39
         A2    WKJNN   1.0 0.2 30 30     78.10     3.07
         A3    WKJNN   0.9 0.2 30 0      69.53     1.56
         A4    KJNN    0.9 0.2 30 30     77.93     3.03
         kj-NN WKJNN   0.9 0.2 30 30     78.10     3.07
arxiv_53 A1    WKJNN   0.9 0.2 0  30     78.55     4.91
         A2    WKJNN   1.0 0.2 30 30     79.16     5.10
         A3    WKJNN   0.9 0.2 30 0      76.48     3.22
         A4    KJNN    0.9 0.2 30 30     79.04     5.08
         kj-NN WKJNN   0.9 0.2 30 30     79.16     5.10
arxiv_54 A1    WKJNN   0.9 0.2 0  30     75.54     3.63
         A2    WKJNN   1.0 0.2 30 30     76.65     3.85
         A3    WKJNN   0.9 0.2 30 0      76.33     3.40
         A4    KJNN    0.9 0.2 30 30     76.54     3.82
         kj-NN WKJNN   0.9 0.2 30 30     76.65     3.85
arxiv_55 A1    WKJNN   0.9 0.2 0  30     75.84     3.07
         A2    WKJNN   1.0 0.2 30 30     76.74     3.22
         A3    WKJNN   0.9 0.2 30 0      72.31     2.24
         A4    KJNN    0.9 0.2 30 30     76.60     3.18
         kj-NN WKJNN   0.9 0.2 30 30     76.74     3.22
nyt_1    A1    WKJNN   0.9 0.2 0  30     89.57    16.65
         A2    WKJNN   1.0 0.2 30 30     92.51    17.57
         A3    WKJNN   0.9 0.2 30 0      90.56     8.45
         A4    KJNN    0.9 0.2 30 30     92.48    17.07
         kj-NN WKJNN   0.9 0.2 30 30     92.51    17.57
nyt_10   A1    WKJNN   0.9 0.2 0  30     91.25     8.05
         A2    WKJNN   1.0 0.2 30 30     91.52     8.45
         A3    WKJNN   0.9 0.2 30 0      89.65    14.06
         A4    KJNN    0.9 0.2 30 30     91.23     8.49
         kj-NN WKJNN   0.9 0.2 30 30     91.52     8.45
nyt_2    A1    WKJNN   0.9 0.2 0  30     93.29    43.23
         A2    WKJNN   1.0 0.2 30 30     94.51    42.64
         A3    WKJNN   0.9 0.2 30 0      91.23    18.62
         A4    KJNN    0.9 0.2 30 30     94.50    42.12
         kj-NN WKJNN   0.9 0.2 30 30     94.51    42.64
nyt_20   A1    WKJNN   0.9 0.2 0  30     89.01     5.94
         A2    WKJNN   1.0 0.2 30 30     91.42     6.57
         A3    WKJNN   0.9 0.2 30 0      89.93     9.45
         A4    KJNN    0.9 0.2 30 30     91.42     6.51
         kj-NN WKJNN   0.9 0.2 30 30     91.42     6.57
nyt_5    A1    WKJNN   0.9 0.2 0  30     96.61    72.33
         A2    WKJNN   1.0 0.2 30 30     97.04    71.69
         A3    WKJNN   0.9 0.2 30 0      92.33    41.43
         A4    KJNN    0.9 0.2 30 30     97.04    71.63
         kj-NN WKJNN   0.9 0.2 30 30     97.04    71.69
nyt_50   A1    WKJNN   0.9 0.2 0  30     91.20    27.29
         A2    WKJNN   1.0 0.2 30 30     93.33    27.76
         A3    WKJNN   0.9 0.2 30 0      90.78    13.34
         A4    KJNN    0.9 0.2 30 30     93.30    27.44
         kj-NN WKJNN   0.9 0.2 30 30     93.33    27.76

In [19]:
output = subdata[subdata["A"] == "kj-NN"].groupby(["dataset", "A", "scoreId", "p", "c", "j", "k"])[att + times].mean()

attsmall = ['typeAprecision', 'typeArecall', "A-F1", 
       'typeBprecision', 'typeBrecall', "B-F1"]
att = ['typeAprecision', 'typeArecall', "A-F1", 
       'typeBprecision', 'typeBrecall', "B-F1", 
       "typeAauc", "typeAap", "typeAr1", "typeAr2", "typeAr5",
      "typeBr10", "typeBr20"]
output[att] = round(output[att]*100,2)

times = ['cpu', 'wall', 'cpurep', 'cpuindex', 'cpucache']
output[times] = round(output[times] / 1000,2)

output[["typeAauc", "typeAap", "typeAr1", "typeAr2", "typeAr5"]]

,,,,,,,typeAauc,typeAap,typeAr1,typeAr2,typeAr5
dataset,A,scoreId,p,c,j,k,,,,,
arxiv_15,kj-NN,WKJNN,0.9,0.2,30,30,54.21,1.17,0.00,0.00,0.00
arxiv_25,kj-NN,WKJNN,0.9,0.2,30,30,70.64,5.10,10.44,16.52,27.82
arxiv_35,kj-NN,WKJNN,0.9,0.2,30,30,73.58,3.27,6.45,10.97,20.97
arxiv_45,kj-NN,WKJNN,0.9,0.2,30,30,69.94,3.28,6.46,9.09,18.99
arxiv_51,kj-NN,WKJNN,0.9,0.2,30,30,65.24,2.19,4.68,7.90,14.36
arxiv_52,kj-NN,WKJNN,0.9,0.2,30,30,78.10,3.07,3.87,7.90,19.35
arxiv_53,kj-NN,WKJNN,0.9,0.2,30,30,79.16,5.10,7.74,15.65,32.42
arxiv_54,kj-NN,WKJNN,0.9,0.2,30,30,76.65,3.85,5.81,10.00,21.61
arxiv_55,kj-NN,WKJNN,0.9,0.2,30,30,76.74,3.22,5.49,9.84,20.48
nyt_1,kj-NN,WKJNN,0.9,0.2,30,30,92.51,17.57,25.00,39.20,61.40
nyt_10,kj-NN,WKJNN,0.9,0.2,30,30,91.52,8.45,10.00,16.00,38.00
nyt_2,kj-NN,WKJNN,0.9,0.2,30,30,94.51,42.64,30.40,44.50,64.50
nyt_20,kj-NN,WKJNN,0.9,0.2,30,30,91.42,6.57,3.00,11.00,38.00
nyt_5,kj-NN,WKJNN,0.9,0.2,30,30,97.04,71.69,19.12,36.96,68.28
nyt_50,kj-NN,WKJNN,0.9,0.2,30,30,93.33,27.76,37.20,46.80,62.80

In [20]:
output = subdata[subdata["A"] == "kj-NN"].groupby(["dataset", "A", "scoreId", "p", "c", "j", "k"])[att + times].mean()

attsmall = ['typeAprecision', 'typeArecall', "A-F1", 
       'typeBprecision', 'typeBrecall', "B-F1"]
att = ['typeAprecision', 'typeArecall', "A-F1", 
       'typeBprecision', 'typeBrecall', "B-F1", 
       "typeAauc", "typeAap", "typeAr1", "typeAr2", "typeAr5",
      "typeBr10", "typeBr20"]
output[att] = round(output[att]*100,2)

times = ['cpu', 'wall', 'cpurep', 'cpuindex', 'cpucache']
output[times] = round(output[times] / 1000,2)

output[["typeBprecision", "typeBrecall", "B-F1", "typeBr10", "typeBr20"]]

,,,,,,,typeBprecision,typeBrecall,B-F1,typeBr10,typeBr20
dataset,A,scoreId,p,c,j,k,,,,,
arxiv_15,kj-NN,WKJNN,0.9,0.2,30,30,0.00,0.00,NaN,0.00,0.00
arxiv_25,kj-NN,WKJNN,0.9,0.2,30,30,96.09,88.85,92.33,49.22,88.85
arxiv_35,kj-NN,WKJNN,0.9,0.2,30,30,80.04,86.98,83.36,48.25,83.40
arxiv_45,kj-NN,WKJNN,0.9,0.2,30,30,70.29,86.87,77.70,45.78,76.89
arxiv_51,kj-NN,WKJNN,0.9,0.2,30,30,70.91,88.63,78.79,46.25,78.18
arxiv_52,kj-NN,WKJNN,0.9,0.2,30,30,71.08,88.43,78.81,47.28,78.79
arxiv_53,kj-NN,WKJNN,0.9,0.2,30,30,70.77,88.46,78.63,46.69,78.24
arxiv_54,kj-NN,WKJNN,0.9,0.2,30,30,70.38,88.05,78.23,46.83,77.78
arxiv_55,kj-NN,WKJNN,0.9,0.2,30,30,70.70,88.23,78.50,46.77,78.67
nyt_1,kj-NN,WKJNN,0.9,0.2,30,30,95.93,90.02,92.88,50.19,90.02
nyt_10,kj-NN,WKJNN,0.9,0.2,30,30,88.57,90.77,89.65,50.50,89.97
nyt_2,kj-NN,WKJNN,0.9,0.2,30,30,94.63,91.15,92.86,50.74,91.15
nyt_20,kj-NN,WKJNN,0.9,0.2,30,30,93.80,90.64,92.19,50.52,90.64
nyt_5,kj-NN,WKJNN,0.9,0.2,30,30,92.43,93.44,92.93,52.27,93.44
nyt_50,kj-NN,WKJNN,0.9,0.2,30,30,95.78,90.36,92.99,50.22,90.36

In [21]:
subdata = masterdata[(masterdata["k"] == 30) & ((masterdata["j"] == 30) ) # | (masterdata["j"] == 0)
                    & (masterdata["c"] == 0.2)& 
                     ([x in [0.9] for x in masterdata["p"]])]

In [22]:
subdata["cpu"] = round(subdata["cpu"] / 1000,2)

/home/fouchee/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [23]:
subdata["B-F1"] = 2* (subdata["typeBrecall"]*subdata["typeBprecision"]) / (subdata["typeBrecall"]+subdata["typeBprecision"])

/home/fouchee/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [24]:
att = ["typeBprecision", "typeBrecall", "B-F1", "typeBr10", "typeBr20"]
a = subdata.groupby(["dataset", "p", "c", "j"])[att].mean()

a[att] = round(a[att]*100,2)
a[["typeBprecision", "typeBrecall", "B-F1", "typeBr10", "typeBr20"]]

                     typeBprecision  typeBrecall   B-F1  typeBr10  typeBr20
dataset  p   c   j
arxiv_15 0.9 0.2 30            0.00         0.00    NaN      0.00      0.00
arxiv_25 0.9 0.2 30           96.09        88.91  92.36     49.22     88.91
arxiv_35 0.9 0.2 30           79.98        86.99  83.33     48.24     83.36
arxiv_45 0.9 0.2 30           70.19        86.88  77.65     45.75     76.79
arxiv_51 0.9 0.2 30           70.86        88.65  78.76     46.22     78.14
arxiv_52 0.9 0.2 30           70.99        88.44  78.76     47.25     78.68
arxiv_53 0.9 0.2 30           70.71        88.49  78.60     46.67     78.22
arxiv_54 0.9 0.2 30           70.29        88.03  78.16     46.81     77.71
arxiv_55 0.9 0.2 30           70.59        88.21  78.42     46.74     78.58
nyt_1    0.9 0.2 30           95.91        90.01  92.87     50.18     90.01
nyt_10   0.9 0.2 30           88.38        90.67  89.51     50.50     89.87
nyt_2    0.9 0.2 30           94.59        91.11  92.82     50.75     91.11
nyt_20   0.9 0.2 30           93.70        90.57  92.10     50.52     90.57
nyt_5    0.9 0.2 30           92.33        93.45  92.89     52.26     93.45
nyt_50   0.9 0.2 30           95.71        90.35  92.95     50.21     90.35

In [25]:
subdata["A-F1"] = 2* (subdata["typeArecall"]*subdata["typeAprecision"]) / (subdata["typeArecall"]+subdata["typeAprecision"])

/home/fouchee/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [26]:
subdata.groupby(["dataset", "p", "c", "j"])["k", "ndocs", "cpu", 
                                            "typeArecall", "typeAprecision", "A-F1",
                                       "typeAr1", "typeAr2", "typeAr5"].mean()

,,,,k,ndocs,cpu,typeArecall,typeAprecision,A-F1,typeAr1,typeAr2,typeAr5
dataset,p,c,j,,,,,,,,,
arxiv_15,0.9,0.2,30,30,3919,124.765,0.00000,0.00000,NaN,0.00000,0.00000,0.00000
arxiv_25,0.9,0.2,30,30,4596,151.603,0.38696,0.03878,0.070495,0.10219,0.16306,0.27607
arxiv_35,0.9,0.2,30,30,6233,213.726,0.30323,0.03018,0.054896,0.06452,0.10807,0.20805
arxiv_45,0.9,0.2,30,30,10003,342.264,0.31613,0.03130,0.056960,0.06363,0.09292,0.18887
arxiv_51,0.9,0.2,30,30,12564,377.076,0.25161,0.02486,0.045249,0.04680,0.07822,0.14276
arxiv_52,0.9,0.2,30,30,12564,395.242,0.35162,0.03470,0.063166,0.03872,0.07580,0.19031
arxiv_53,0.9,0.2,30,30,12564,375.692,0.50161,0.04954,0.090174,0.07742,0.15648,0.32178
arxiv_54,0.9,0.2,30,30,12564,315.690,0.37177,0.03668,0.066772,0.05889,0.09836,0.21451
arxiv_55,0.9,0.2,30,30,12564,354.318,0.35403,0.03494,0.063603,0.05567,0.09676,0.20241
nyt_1,0.9,0.2,30,30,10100,210.351,0.77600,0.07680,0.139767,0.24600,0.38900,0.61100
nyt_10,0.9,0.2,30,30,1010,31.546,0.61000,0.06039,0.109900,0.10000,0.17000,0.37000
nyt_2,0.9,0.2,30,30,10200,136.988,0.80000,0.15687,0.262305,0.30350,0.44250,0.64450
nyt_20,0.9,0.2,30,30,2020,52.895,0.65000,0.06438,0.117156,0.03000,0.10500,0.37000
nyt_5,0.9,0.2,30,30,10500,163.893,0.85880,0.40896,0.554072,0.19140,0.36920,0.68280
nyt_50,0.9,0.2,30,30,5050,85.699,0.80200,0.07940,0.144495,0.37200,0.46800,0.63000